### ISSUE TITLE
The getter 'onComplete' was called on null

### ISSUE THREAD

**Issue by noelmathewisaac** [atn832/firebase_storage_mocks#1]
When I run the example code, the putFile method always returns null. I also tried using the putData method instead but it results in the same error which is:
 ```
NoSuchMethodError: The getter 'onComplete' was called on null.
 Receiver: null
 Tried calling: onComplete
```
Any help will be appreciated.
Thank you.

**Comment by LHDi** [comment]
Any progress???

**Comment by atn832** [comment]
Would you mind sharing the exact code you tried to run, and which version of the firebase_storage_mocks you used? The unit tests at https://github.com/atn832/firebase_storage_mocks/blob/master/test/firebase_storage_mocks_test.dart still run fine.

**Comment by atn832** [comment]
Please feel free to reopen with failing test code if it still happens.
