### ISSUE TITLE
No implementation of MockStorageReference.getDownloadURL

### ISSUE THREAD

**Issue by ChopinDavid** [atn832/firebase_storage_mocks#10]
I've gone ahead and forked this repo and [implemented `getDownloadURL` within `MockStorageReference`](https://github.com/ChopinDavid/firebase_storage_mocks/commit/c228e8a4b29ac9b6ba91571223f7705e0c45cb06). It seems that there is no way, AFAIK, to construct a download url that is similar to an actual Firebase Storage download URL (`https://firebasestorage.googleapis.com/v0/b/{your-application}.appspot.com/o/{url-encoded-path-name}?alt=media&token={your-token}`) so I have it returning a dummy value instead (`https://firebasestorage.googleapis.com/{path}`). This dummy value could be updated so that `_path` is url encoded when interpolated into the download URL path that the function returns. Also, there could probably also be a test written around this, but I didn't see any Mock Reference tests.

Let me know if you are interested in me creating a PR for my fork.

**Comment by cedvdb** [comment]
yes the pr would be nice
