### ISSUE TITLE
Typo: Usage example errors

### ISSUE THREAD

**Issue by jarrodonlo** [atn832/firebase_storage_mocks#14]
The current **Usage** example in [README.md](https://github.com/atn832/firebase_storage_mocks/blob/master/README.md) instantiates `MockFirebaseStorage('someimage.png');`; however, `MockFirebaseStorage` has zero parameters (though in example here it is given 'someimage.png'.)

I plan on creating a PR that fixes this and a few other items in usage example.

**Comment by jarrodonlo** [comment]
see pr https://github.com/atn832/firebase_storage_mocks/pull/15

**Comment by atn832** [comment]
Fixed by #15.
