### ISSUE TITLE
Versions incompatible

### ISSUE THREAD

**Issue by felixwortmann** [atn832/firebase_storage_mocks#7]
This package is incompatible with [cloud_firestore_mocks](https://pub.dev/packages/cloud_firestore_mocks) because of this error:

```
Because no versions of cloud_firestore_mocks match >0.8.0 <0.9.0 and cloud_firestore_mocks 0.8.0 depends on mockito ^5.0.0, cloud_firestore_mocks ^0.8.0 requires mockito ^5.0.0.

And because every version of firebase_storage_mocks depends on mockito ^4.1.0, cloud_firestore_mocks ^0.8.0 is incompatible with firebase_storage_mocks.
```

If I override the dependency to `mockito ^5.0.0`, I get the next error:
```
Because firebase_storage_mocks >=0.2.0 depends on firebase_storage ^4.0.0 and my_app depends on firebase_storage ^8.0.0, firebase_storage_mocks >=0.2.0 is forbidden.
```
So it also seems to be incompatible with the current version of `firebase_storage`

<br>
I think just bumping both versions should do the trick, unless there were some breaking changes.

**Comment by atn832** [comment]
Fixed by #8. You can get it at https://pub.dev/packages/firebase_storage_mocks/changelog#030.
